/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beetSolana from '@metaplex-foundation/beet-solana'
import * as beet from '@metaplex-foundation/beet'

/**
 * Arguments used to create {@link Bonus}
 * @category Accounts
 * @category generated
 */
export type BonusArgs = {
  authority: web3.PublicKey
  bump: number
  vaultBump: number
}

export const bonusDiscriminator = [198, 155, 31, 171, 113, 36, 189, 12]
/**
 * Holds the data for the {@link Bonus} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
export class Bonus implements BonusArgs {
  private constructor(
    readonly authority: web3.PublicKey,
    readonly bump: number,
    readonly vaultBump: number,
  ) {}

  /**
   * Creates a {@link Bonus} instance from the provided args.
   */
  static fromArgs(args: BonusArgs) {
    return new Bonus(args.authority, args.bump, args.vaultBump)
  }

  /**
   * Deserializes the {@link Bonus} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static fromAccountInfo(
    accountInfo: web3.AccountInfo<Buffer>,
    offset = 0,
  ): [Bonus, number] {
    return Bonus.deserialize(accountInfo.data, offset)
  }

  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link Bonus} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  static async fromAccountAddress(
    connection: web3.Connection,
    address: web3.PublicKey,
    commitmentOrConfig?: web3.Commitment | web3.GetAccountInfoConfig,
  ): Promise<Bonus> {
    const accountInfo = await connection.getAccountInfo(
      address,
      commitmentOrConfig,
    )
    if (accountInfo == null) {
      throw new Error(`Unable to find Bonus account at ${address}`)
    }
    return Bonus.fromAccountInfo(accountInfo, 0)[0]
  }

  /**
   * Provides a {@link web3.Connection.getProgramAccounts} config builder,
   * to fetch accounts matching filters that can be specified via that builder.
   *
   * @param programId - the program that owns the accounts we are filtering
   */
  static gpaBuilder(
    programId: web3.PublicKey = new web3.PublicKey('PROGRAM PUBKEY'),
  ) {
    return beetSolana.GpaBuilder.fromStruct(programId, bonusBeet)
  }

  /**
   * Deserializes the {@link Bonus} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static deserialize(buf: Buffer, offset = 0): [Bonus, number] {
    return bonusBeet.deserialize(buf, offset)
  }

  /**
   * Serializes the {@link Bonus} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  serialize(): [Buffer, number] {
    return bonusBeet.serialize({
      accountDiscriminator: bonusDiscriminator,
      ...this,
    })
  }

  /**
   * Returns the byteSize of a {@link Buffer} holding the serialized data of
   * {@link Bonus}
   */
  static get byteSize() {
    return bonusBeet.byteSize
  }

  /**
   * Fetches the minimum balance needed to exempt an account holding
   * {@link Bonus} data from rent
   *
   * @param connection used to retrieve the rent exemption information
   */
  static async getMinimumBalanceForRentExemption(
    connection: web3.Connection,
    commitment?: web3.Commitment,
  ): Promise<number> {
    return connection.getMinimumBalanceForRentExemption(
      Bonus.byteSize,
      commitment,
    )
  }

  /**
   * Determines if the provided {@link Buffer} has the correct byte size to
   * hold {@link Bonus} data.
   */
  static hasCorrectByteSize(buf: Buffer, offset = 0) {
    return buf.byteLength - offset === Bonus.byteSize
  }

  /**
   * Returns a readable version of {@link Bonus} properties
   * and can be used to convert to JSON and/or logging
   */
  pretty() {
    return {
      authority: this.authority.toBase58(),
      bump: this.bump,
      vaultBump: this.vaultBump,
    }
  }
}

/**
 * @category Accounts
 * @category generated
 */
export const bonusBeet = new beet.BeetStruct<
  Bonus,
  BonusArgs & {
    accountDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['accountDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['authority', beetSolana.publicKey],
    ['bump', beet.u8],
    ['vaultBump', beet.u8],
  ],
  Bonus.fromArgs,
  'Bonus',
)
