/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beetSolana from '@metaplex-foundation/beet-solana'
import * as beet from '@metaplex-foundation/beet'

/**
 * Arguments used to create {@link Governance}
 * @category Accounts
 * @category generated
 */
export type GovernanceArgs = {
  governanceAuthority: web3.PublicKey
  governanceMint: web3.PublicKey
  governanceBonusVault: web3.PublicKey
  feeReduction: number
  fee: number
  sellerPromo: number
  buyerPromo: number
  bump: number
  vaultBump: number
}

export const governanceDiscriminator = [18, 143, 88, 13, 73, 217, 47, 49]
/**
 * Holds the data for the {@link Governance} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
export class Governance implements GovernanceArgs {
  private constructor(
    readonly governanceAuthority: web3.PublicKey,
    readonly governanceMint: web3.PublicKey,
    readonly governanceBonusVault: web3.PublicKey,
    readonly feeReduction: number,
    readonly fee: number,
    readonly sellerPromo: number,
    readonly buyerPromo: number,
    readonly bump: number,
    readonly vaultBump: number,
  ) {}

  /**
   * Creates a {@link Governance} instance from the provided args.
   */
  static fromArgs(args: GovernanceArgs) {
    return new Governance(
      args.governanceAuthority,
      args.governanceMint,
      args.governanceBonusVault,
      args.feeReduction,
      args.fee,
      args.sellerPromo,
      args.buyerPromo,
      args.bump,
      args.vaultBump,
    )
  }

  /**
   * Deserializes the {@link Governance} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static fromAccountInfo(
    accountInfo: web3.AccountInfo<Buffer>,
    offset = 0,
  ): [Governance, number] {
    return Governance.deserialize(accountInfo.data, offset)
  }

  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link Governance} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  static async fromAccountAddress(
    connection: web3.Connection,
    address: web3.PublicKey,
    commitmentOrConfig?: web3.Commitment | web3.GetAccountInfoConfig,
  ): Promise<Governance> {
    const accountInfo = await connection.getAccountInfo(
      address,
      commitmentOrConfig,
    )
    if (accountInfo == null) {
      throw new Error(`Unable to find Governance account at ${address}`)
    }
    return Governance.fromAccountInfo(accountInfo, 0)[0]
  }

  /**
   * Provides a {@link web3.Connection.getProgramAccounts} config builder,
   * to fetch accounts matching filters that can be specified via that builder.
   *
   * @param programId - the program that owns the accounts we are filtering
   */
  static gpaBuilder(
    programId: web3.PublicKey = new web3.PublicKey('PROGRAM PUBKEY'),
  ) {
    return beetSolana.GpaBuilder.fromStruct(programId, governanceBeet)
  }

  /**
   * Deserializes the {@link Governance} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static deserialize(buf: Buffer, offset = 0): [Governance, number] {
    return governanceBeet.deserialize(buf, offset)
  }

  /**
   * Serializes the {@link Governance} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  serialize(): [Buffer, number] {
    return governanceBeet.serialize({
      accountDiscriminator: governanceDiscriminator,
      ...this,
    })
  }

  /**
   * Returns the byteSize of a {@link Buffer} holding the serialized data of
   * {@link Governance}
   */
  static get byteSize() {
    return governanceBeet.byteSize
  }

  /**
   * Fetches the minimum balance needed to exempt an account holding
   * {@link Governance} data from rent
   *
   * @param connection used to retrieve the rent exemption information
   */
  static async getMinimumBalanceForRentExemption(
    connection: web3.Connection,
    commitment?: web3.Commitment,
  ): Promise<number> {
    return connection.getMinimumBalanceForRentExemption(
      Governance.byteSize,
      commitment,
    )
  }

  /**
   * Determines if the provided {@link Buffer} has the correct byte size to
   * hold {@link Governance} data.
   */
  static hasCorrectByteSize(buf: Buffer, offset = 0) {
    return buf.byteLength - offset === Governance.byteSize
  }

  /**
   * Returns a readable version of {@link Governance} properties
   * and can be used to convert to JSON and/or logging
   */
  pretty() {
    return {
      governanceAuthority: this.governanceAuthority.toBase58(),
      governanceMint: this.governanceMint.toBase58(),
      governanceBonusVault: this.governanceBonusVault.toBase58(),
      feeReduction: this.feeReduction,
      fee: this.fee,
      sellerPromo: this.sellerPromo,
      buyerPromo: this.buyerPromo,
      bump: this.bump,
      vaultBump: this.vaultBump,
    }
  }
}

/**
 * @category Accounts
 * @category generated
 */
export const governanceBeet = new beet.BeetStruct<
  Governance,
  GovernanceArgs & {
    accountDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['accountDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['governanceAuthority', beetSolana.publicKey],
    ['governanceMint', beetSolana.publicKey],
    ['governanceBonusVault', beetSolana.publicKey],
    ['feeReduction', beet.u16],
    ['fee', beet.u16],
    ['sellerPromo', beet.u16],
    ['buyerPromo', beet.u16],
    ['bump', beet.u8],
    ['vaultBump', beet.u8],
  ],
  Governance.fromArgs,
  'Governance',
)
