[features]
seeds = true

[programs.localnet]
brick = "BrickarF2QeREBZsapbhgYPHJi5FYkJVnx7mZhxETCt5"

[registry]
url = "https://api.apr.dev"

[test.validator]
url = "https://api.devnet.solana.com"
[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

[provider]
cluster = "Localnet"
wallet = "/Users/riki/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"