[features]
seeds = true

[programs.Mainnet]
brick = "BrickarF2QeREBZsapbhgYPHJi5FYkJVnx7mZhxETCt5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Mainnet"
wallet = "/Users/riki/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"