/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'
import {
  CreateProductParams,
  createProductParamsBeet,
} from '../types/CreateProductParams.js'

/**
 * @category Instructions
 * @category CreateProduct
 * @category generated
 */
export type CreateProductInstructionArgs = {
  params: CreateProductParams
}
/**
 * @category Instructions
 * @category CreateProduct
 * @category generated
 */
export const createProductStruct = new beet.BeetArgsStruct<
  CreateProductInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['params', createProductParamsBeet],
  ],
  'CreateProductInstructionArgs',
)
/**
 * Accounts required by the _createProduct_ instruction
 *
 * @property [_writable_, **signer**] productAuthority
 * @property [] governance
 * @property [_writable_] product
 * @property [] paymentMint
 * @category Instructions
 * @category CreateProduct
 * @category generated
 */
export type CreateProductInstructionAccounts = {
  systemProgram?: web3.PublicKey
  rent?: web3.PublicKey
  productAuthority: web3.PublicKey
  governance: web3.PublicKey
  product: web3.PublicKey
  paymentMint: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const createProductInstructionDiscriminator = [
  183, 155, 202, 119, 43, 114, 174, 225,
]

/**
 * Creates a _CreateProduct_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category CreateProduct
 * @category generated
 */
export function createCreateProductInstruction(
  accounts: CreateProductInstructionAccounts,
  args: CreateProductInstructionArgs,
  programId = new web3.PublicKey('PROGRAM PUBKEY'),
) {
  const [data] = createProductStruct.serialize({
    instructionDiscriminator: createProductInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.rent ?? web3.SYSVAR_RENT_PUBKEY,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.productAuthority,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.governance,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.product,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.paymentMint,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
