/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category DeleteProduct
 * @category generated
 */
export const deleteProductStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number[] /* size: 8 */
}>(
  [['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)]],
  'DeleteProductInstructionArgs',
)
/**
 * Accounts required by the _deleteProduct_ instruction
 *
 * @property [_writable_, **signer**] productAuthority
 * @property [_writable_] product
 * @category Instructions
 * @category DeleteProduct
 * @category generated
 */
export type DeleteProductInstructionAccounts = {
  productAuthority: web3.PublicKey
  product: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const deleteProductInstructionDiscriminator = [
  173, 212, 141, 230, 33, 82, 166, 25,
]

/**
 * Creates a _DeleteProduct_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category DeleteProduct
 * @category generated
 */
export function createDeleteProductInstruction(
  accounts: DeleteProductInstructionAccounts,
  programId = new web3.PublicKey('PROGRAM PUBKEY'),
) {
  const [data] = deleteProductStruct.serialize({
    instructionDiscriminator: deleteProductInstructionDiscriminator,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.productAuthority,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.product,
      isWritable: true,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
