/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'
import {
  EditPointsParams,
  editPointsParamsBeet,
} from '../types/EditPointsParams.js'

/**
 * @category Instructions
 * @category EditPoints
 * @category generated
 */
export type EditPointsInstructionArgs = {
  params: EditPointsParams
}
/**
 * @category Instructions
 * @category EditPoints
 * @category generated
 */
export const editPointsStruct = new beet.BeetArgsStruct<
  EditPointsInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['params', editPointsParamsBeet],
  ],
  'EditPointsInstructionArgs',
)
/**
 * Accounts required by the _editPoints_ instruction
 *
 * @property [_writable_, **signer**] governanceAuthority
 * @property [_writable_] governance
 * @category Instructions
 * @category EditPoints
 * @category generated
 */
export type EditPointsInstructionAccounts = {
  governanceAuthority: web3.PublicKey
  governance: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const editPointsInstructionDiscriminator = [
  9, 164, 47, 125, 181, 202, 77, 193,
]

/**
 * Creates a _EditPoints_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category EditPoints
 * @category generated
 */
export function createEditPointsInstruction(
  accounts: EditPointsInstructionAccounts,
  args: EditPointsInstructionArgs,
  programId = new web3.PublicKey('PROGRAM PUBKEY'),
) {
  const [data] = editPointsStruct.serialize({
    instructionDiscriminator: editPointsInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.governanceAuthority,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.governance,
      isWritable: true,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
