/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category RegisterPromoBuy
 * @category generated
 */
export const registerPromoBuyStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number[] /* size: 8 */
}>(
  [['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)]],
  'RegisterPromoBuyInstructionArgs',
)
/**
 * Accounts required by the _registerPromoBuy_ instruction
 *
 * @property [] messagesProgram
 * @property [] governanceAuthority
 * @property [_writable_, **signer**] signer
 * @property [_writable_] governance
 * @property [] product
 * @property [] governanceMint
 * @property [_writable_] buyerTransferVault
 * @property [_writable_] productAuthorityTransferVault
 * @property [_writable_] governanceTransferVault
 * @property [_writable_] governanceBonusVault
 * @property [_writable_] productAuthorityBonus
 * @property [_writable_] productAuthorityBonusVault
 * @property [_writable_] buyerBonus
 * @property [_writable_] buyerBonusVault
 * @category Instructions
 * @category RegisterPromoBuy
 * @category generated
 */
export type RegisterPromoBuyInstructionAccounts = {
  systemProgram?: web3.PublicKey
  messagesProgram: web3.PublicKey
  tokenProgram?: web3.PublicKey
  rent?: web3.PublicKey
  governanceAuthority: web3.PublicKey
  signer: web3.PublicKey
  governance: web3.PublicKey
  product: web3.PublicKey
  governanceMint: web3.PublicKey
  buyerTransferVault: web3.PublicKey
  productAuthorityTransferVault: web3.PublicKey
  governanceTransferVault: web3.PublicKey
  governanceBonusVault: web3.PublicKey
  productAuthorityBonus: web3.PublicKey
  productAuthorityBonusVault: web3.PublicKey
  buyerBonus: web3.PublicKey
  buyerBonusVault: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const registerPromoBuyInstructionDiscriminator = [
  74, 129, 38, 224, 112, 1, 195, 137,
]

/**
 * Creates a _RegisterPromoBuy_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category RegisterPromoBuy
 * @category generated
 */
export function createRegisterPromoBuyInstruction(
  accounts: RegisterPromoBuyInstructionAccounts,
  programId = new web3.PublicKey('PROGRAM PUBKEY'),
) {
  const [data] = registerPromoBuyStruct.serialize({
    instructionDiscriminator: registerPromoBuyInstructionDiscriminator,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.messagesProgram,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.rent ?? web3.SYSVAR_RENT_PUBKEY,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.governanceAuthority,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.signer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.governance,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.product,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.governanceMint,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.buyerTransferVault,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.productAuthorityTransferVault,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.governanceTransferVault,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.governanceBonusVault,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.productAuthorityBonus,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.productAuthorityBonusVault,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.buyerBonus,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.buyerBonusVault,
      isWritable: true,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
