/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category WithdrawBonus
 * @category generated
 */
export const withdrawBonusStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number[] /* size: 8 */
}>(
  [['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)]],
  'WithdrawBonusInstructionArgs',
)
/**
 * Accounts required by the _withdrawBonus_ instruction
 *
 * @property [_writable_, **signer**] signer
 * @property [] governance
 * @property [_writable_] bonus
 * @property [] governanceMint
 * @property [_writable_] governanceBonusVault
 * @property [_writable_] receiverVault
 * @property [_writable_] bonusVault
 * @category Instructions
 * @category WithdrawBonus
 * @category generated
 */
export type WithdrawBonusInstructionAccounts = {
  tokenProgram?: web3.PublicKey
  signer: web3.PublicKey
  governance: web3.PublicKey
  bonus: web3.PublicKey
  governanceMint: web3.PublicKey
  governanceBonusVault: web3.PublicKey
  receiverVault: web3.PublicKey
  bonusVault: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const withdrawBonusInstructionDiscriminator = [
  112, 110, 149, 206, 101, 110, 1, 232,
]

/**
 * Creates a _WithdrawBonus_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category WithdrawBonus
 * @category generated
 */
export function createWithdrawBonusInstruction(
  accounts: WithdrawBonusInstructionAccounts,
  programId = new web3.PublicKey('PROGRAM PUBKEY'),
) {
  const [data] = withdrawBonusStruct.serialize({
    instructionDiscriminator: withdrawBonusInstructionDiscriminator,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.signer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.governance,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.bonus,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.governanceMint,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.governanceBonusVault,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.receiverVault,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.bonusVault,
      isWritable: true,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
