/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
export type CreateGovernanceParams = {
  fee: number
  feeReduction: number
  sellerPromo: number
  buyerPromo: number
}

/**
 * @category userTypes
 * @category generated
 */
export const createGovernanceParamsBeet =
  new beet.BeetArgsStruct<CreateGovernanceParams>(
    [
      ['fee', beet.u16],
      ['feeReduction', beet.u16],
      ['sellerPromo', beet.u16],
      ['buyerPromo', beet.u16],
    ],
    'CreateGovernanceParams',
  )
